### ISSUE TITLE
Prijedlog za nadopunu README.md

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/GNSS-GPS-L86-M33-breakout-hardware-design#1]
https://github.com/SolderedElectronics/GNSS-GPS-L86-M33-breakout-hardware-design/blob/1bc7b23ac9562bf88b86c5d5c11397a9f29d28c2/README.md?plain=1#L1

umjesto:

## --- Product name --- Hardware design

predlažem:

# GNSS GPS L86-M33 breakout Hardware design

https://github.com/SolderedElectronics/GNSS-GPS-L86-M33-breakout-hardware-design/blob/1bc7b23ac9562bf88b86c5d5c11397a9f29d28c2/README.md?plain=1#L3

umjesto:

| ![Product name](https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg) |

predlažem:

| ![GNSS GPS L86-M33 breakout](https://github.com/SolderedElectronics/GNSS-GPS-L86-M33-breakout-hardware-design/blob/main/OUTPUTS/V1.2.0/333201.jpg?raw=true) |

https://github.com/SolderedElectronics/GNSS-GPS-L86-M33-breakout-hardware-design/blob/1bc7b23ac9562bf88b86c5d5c11397a9f29d28c2/README.md?plain=1#L5

umjesto:

|      [--- product name ----](https://www.solde.red/SKU)      |

predlažem:

|      [Buy GNSS GPS L86-M33 breakout](https://www.solde.red/333201)      |

https://github.com/SolderedElectronics/GNSS-GPS-L86-M33-breakout-hardware-design/blob/1bc7b23ac9562bf88b86c5d5c11397a9f29d28c2/README.md?plain=1#L7

umjesto:

------ product description ------

predlažem:

Global Navigation Satellite Systems (GNSS), or as we all like to call it “GPS,” enable precise location determination on Earth. Thanks to this module, you can use GNSS for your project and employ the device for asset tracking or create a wearable device. The module is small, energy-efficient, highly effective, and easy to use thanks to its built-in antenna.

L86-M33 is a GNSS receiver, meaning it can receive signals from GPS, GLONASS, and Galileo constellations. Equipped with EASY (Embedded Assist System for self-generated orbit prediction) and AlwaysLocate technologies, the L86-M33 ensures fast and accurate positioning even in challenging environments. Its advanced internal logger, LOCUS, allows you to store your routes and location data.

In addition to the aforementioned L86-M33 module, which has an integrated antenna, our breakout board also has a connector for a CR1220 battery that is used as a backup for timekeeping and GPS data. The module can operate without a battery, but each time it will have to pull data from the satellites anew (cold start). If the integrated antenna is not sufficient, there is an IPX connector on the board for adding an external, stronger antenna. You can find the antenna we recommend [here](https://soldered.com/product/active-gps-antenna-sma-connector/). To easily access the pins of the module, the pins are exposed on the board for easy access.

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
